name: Build ROM

on: [push]

jobs:
  build_rom:
    runs-on: ubuntu-latest
    name: Compile ROM
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Get dependency packages
        # run: sudo apt update && sudo apt install ninja-build
      - name: Get asar
        run: make asar CMAKE_ASAR_GENERATOR="Unix Makefiles"
      - name: Build ROM
        run: make build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ROM.zip
          path: out/*
